### ISSUE TITLE
Mistagged CMake library version

### ISSUE THREAD

**Issue by AbrilRBS** [vahancho/erkir#11]
Hi!

Just wanted to give you a heads up that while adding support for the new version of the library in Conan Center Index in https://github.com/conan-io/conan-center-index/pull/23224, we realized that the CMake file lists the wrong version of the library from what was later tagged as 2.1.0 in https://github.com/vahancho/erkir/blob/master/CMakeLists.txt#L9 :)

**Comment by vahancho** [comment]
@RubenRBS Thank you for letting me know. I've fixed the versioning.
