### ISSUE TITLE
It seems like point is not in decimal degrees but in degrees dot decimal minutes

### ISSUE THREAD

**Issue by Laro88** [vahancho/erkir#2]
It got some crazy jumps so I just checked with OpenCPN and it concurs with my findings. Setting OpenCPN to degrees, decimal minutes correspons to Point.latitude().degrees()

**Comment by Laro88** [comment]
Apologies, Erkir is ok, the problem was found to be inside my generation of NMEA strings - I did not respect the correct formatting of the content.

**Comment by vahancho** [comment]
Thank you for clarification.
