### ISSUE TITLE
change target_include_directories() to use PUBLIC_instead of PRIVATE

### ISSUE THREAD

**Issue by lgwest** [vahancho/erkir#3]
`target_include_directories(erkir PUBLIC include)`  make it easier to use this library. 
It will then be enough to write `target_link_libraries(<target> erkir)` and the include directory will be accessible automatically.
But as it is now one have to specify erkir include dir manually with e.g include_libraries().

**Comment by vahancho** [comment]
Hi,

Are you referring to [this](https://github.com/vahancho/erkir/blob/master/CMakeLists.txt#L30) line?

**Comment by lgwest** [comment]
Yes

Den mån 23 nov. 2020 16:27Vahan Aghajanyan <notifications@github.com> skrev:

**Comment by lgwest** [comment]
maybe also add a namespace alias line:
`add_library(erkir::erkir ALIAS erkir)`
I found some info about that [her](https://stackoverflow.com/questions/46567646/cmake-usefulness-of-aliases) and [here](https://www.youtube.com/watch?v=bsXLMQ6WgIk)

**Comment by vahancho** [comment]
The proposed changes have been [added](https://github.com/vahancho/erkir/commit/ee5655a1ed7200527365666a2443b5ab07aa52fa).
