### ISSUE TITLE
Replace CMAKE_SOURCE_DIR with CMAKE_CURRENT_SOURCE_DIR

### ISSUE THREAD

**Issue by carlocorradini** [vahancho/erkir#5]
`CMake` is currently configured to use `CMAKE_SOURCE_DIR`
Conflicts may arise when the library is imported (for example, using [CPM](https://github.com/cpm-cmake/CPM.cmake))
It is necessary to change every instance of `CMAKE_SOURCE_DIR` to `CMAKE_CURRENT_SOURCE_DIR` in order to prevent the latter

**Comment by vahancho** [comment]
Thank you for reporting this issue and your participation.
