### ISSUE TITLE
Height discrepancy and Helmert transformation

### ISSUE THREAD

**Issue by KrukDallan** [vahancho/erkir#9]
Good morning!

I am using your library and I think I have encountered a discrepancy regarding the heightof a point when converted into a different coordinate standard (i.e. when chaning its datum). In particular, if I define a point as 

```cpp
erkir::ellipsoidal::Point greenwichWGS84(51.47788, -0.00147, 0.0, erkir::ellipsoidal::Datum::Type::WGS84);
```

and then I convert it to the `OSGB36` standard, I obtain an height of `-45.9051`.

**_Is this result the correct height, maybe because we are in a different standard? Or is there a mistake somewhere?_**

Also, in the wikipedia page the Helmert transformation is defined as:

![image](https://github.com/vahancho/erkir/assets/99502048/9d619aa0-6222-47c6-9b11-98733fc241bf)

while in your code it is written slightly differently. Is there a reason for that?

Thank you in advance! 🙏

**Comment by vahancho** [comment]
Hi,

Thank you for the question. I've double checked the conversion with[ another tool](https://www.howtocreate.co.uk/php/gpstogrid.php?initial=gps&gps=51.47788%2C+-0.00147&gpsalt=0&gpsx=&gpsy=&gpsz=&etrsx=&etrsy=&etrsz=&etrs=&etrsalt=&grid=&gridalt=&date=2023-11-30&etrsframe=etrf97&variance=38422137+&exponent=r640204335227799u100599794153553952&covariance=&subvariance=1) and the result looks very close to what you observe:

```
(Basic Helmert transformation gave TQ38884.99738577329.260052-45.904998.
That is an error of 2.497462 m, of which 2.444854 m is horizontal, and 0.509903 m is vertical.)
```

For more details about the algorithm please refer to [this ](https://www.movable-type.co.uk/scripts/latlong-os-gridref.html)page. This library is just a C++ port of the original JavaScript code.

**Comment by KrukDallan** [comment]
Does this mean that the height (aka altitude) is correct in the `OSGB36` coordinate standard? If yes, could you please explain me why? I have not found any answer onthe internet.

Also, when I make the conversion back to  `WGS84` from  `OSGB36`, the height (altitude) measures circa -571. Is this expected?

By the way, I didn't told you this in the first message, but a collegue of mine "added" the computation of the altitude starting from the code you have written, so if you were wondering how we computed it, well that's how :D 

Thank you in advance for the asnwer

**Comment by vahancho** [comment]
The only answer I have at the moment is that the computation is based on the different [ellipsoidal models](https://github.com/vahancho/erkir/blob/339fbc9d00c9c75f4291fe547b1d03df260edcb0/src/datum.cpp#L172C34-L172C34). As a result the same point may have different height depending on the datum.
Again, the [original page](https://www.movable-type.co.uk/scripts/latlong-os-gridref.html) describes the theory behind the calculations and explains how the conversion is made.

**Comment by KrukDallan** [comment]
Thank you again for the answers!
